version: 2
references:
  cache_key: &cache_key
    key: cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.m2
        - ~/.gradle
  workspace: &workspace ~/workspace
  attach_debug_workspace: &attach_debug_workspace
    attach_workspace:
      at: *workspace
  attach_release_workspace: &attach_release_workspace
    attach_workspace:
      at: *workspace
  persist_debug_workspace: &persist_debug_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - .
  persist_release_workspace: &persist_release_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - .
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
      JVM_OPTS: "-Xmx3200m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx3200m"'
jobs:
  test_app_unit:
    <<: *android_config
    steps:
      - *attach_debug_workspace
      - checkout
      - *restore_cache
      - run:
          name: Running unit tests
          command: ./gradlew test --no-daemon
      - *save_cache
      - *persist_debug_workspace
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  build_app:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - run: yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true
      - run: ./gradlew --stop
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon
      - run:
          name: Run Build
          command: ./gradlew cleanBuildCache clean assemble assembleAndroidTest --rerun-tasks --no-daemon
      - *save_cache
      - *persist_debug_workspace
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
workflows:
  version: 2
  workflow:
    jobs:
      - build_app
      - test_app_unit:
          requires:
            - build_app